- name: Download IntelliJ
  command: 'xdg-open https://www.jetbrains.com/idea/download/download-thanks.html?platform=linuxWithoutJDK'
  args:
    creates: /home/rook/lock/intellij_installer.lock

- name: Create file so we don't open the IntelliJ download link again
  file:
    path: /home/rook/lock/intellij_installer.lock
    state: touch

- name: Install NPM Tools
  become: yes
  npm:
    name: '{{ item }}'
    global: yes
  with_items: 
      - '@vue/cli'
