- name: Install packages required by dev tools
  become: yes
  apt:
    name:
      - python-apt
      - python3-apt
      - python3-pip
      - apt-transport-https # Docker
      - ca-certificates # Docker
      - curl # Docker
      - gnupg-agent # Docker
      - software-properties-common # Docker
      - postgresql-client

- name: Download IntelliJ
  command: 'xdg-open https://www.jetbrains.com/idea/download/download-thanks.html?platform=linuxWithoutJDK'
  args:
    creates: /home/rook/lock/intellij_installer.lock

- name: Create file so we don't open the IntelliJ download link again
  file:
    path: /home/rook/lock/intellij_installer.lock
    state: touch

- name: Install NPM Tools
  become: yes
  npm:
    name: '{{ item }}'
    global: yes
  with_items: 
      - '@vue/cli'

- name: Add PPA for Atom text editor
  become: yes
  apt_repository:
    repo: ppa:webupd8team/atom
    codename: bionic

- name: Install Atom text editor from PPA
  become: yes
  apt:
    name: atom

- name: Add GPG Key for Docker 
  become: yes
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Repo for Docker CE
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    state: present

- name: Apt install Docker CE
  become: yes
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Install Docker Compose
  become: yes
  pip:
    executable: pip3
    name: docker-compose
