- name: Remove unwanted default applications
  become: yes
  apt:
    autoclean: yes
    autoremove: yes
    state: absent
    name:
      - unity-webapps-common
      - rhythmbox

- name: Set up SSH Keys
  user:
    name: rook
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: Create ~/git Directory
  file:
    state: directory
    path: ~/{{ item }}
    owner: rook
    group: rook
  with_items:
    - git
    - lock

- name: Checkout Profile from Github
  git:
    repo: https://github.com/douglasryanadams/config.git
    dest: ~/git/config
    update: no

- name: Set ownership of ~/git/config
  file:
    path: ~/git/config
    owner: rook
    group: rook
    recurse: true

- name: Symlink Profile into Home Directory
  file:
    state: link
    src: ~/git/config/{{ item }}
    dest: ~/{{ item }}
    owner: rook
    group: rook
    force: true
  with_items:
    - .profile
    - .gitconfig
    - .gitignore

- name: Run script to send ad servers to 0.0.0.0
  script: ~/git/config/scripts/hosts.py
  become: yes
  args:
    creates: /tmp/hosts_updated.lock

- name: Create file to prevent hosts script from running again
  file:
    path: /tmp/hosts_updated.lock
    state: touch

